  - name: "copy fqdn file of node1 to master"
    copy:
      dest: /fqdn1.txt
      src: ./fqdn1.txt

  - name: "copy fqdn file of node2 to master"
    copy:
      dest: /fqdn2.txt
      src: ./fqdn2.txt

  - name: "copy secrets file"
    copy:
      dest: /Mysecret.yml
      src: Mysecret.yml

  - name: "copy wordpress deployment file to master"
    copy:
      dest: /wordpressDeploy.yml
      src: wordpressDeploy.yml

  - name: "copy mysql deployment file to master"
    copy:
      dest: /mysqlDeploy.yml
      src: mysqlDeploy.yml
  
  - name: "copy wordpress service file to master"
    copy:
      dest: /wordpress_Expose_svc.yml
      src: wordpress_Expose_svc.yml

  - name: "give label to node1"
    shell: kubectl label nodes `cat /fqdn1.txt` frontend=wordpress
    ignore_errors: yes

  - name: "give label to node2"
    shell: kubectl label nodes `cat /fqdn2.txt` backend=mysql
    ignore_errors: yes

  - name: "create Secrets File"
    shell: kubectl apply -f /Mysecret.yml

  - name: "create deployment for wordpress"
    shell: kubectl apply -f /wordpressDeploy.yml

  - name: "create deployment for mysql"
    shell: kubectl apply -f /mysqlDeploy.yml

  - name: "expose wordpress deployment"
    shell: kubectl apply -f /wordpress_Expose_svc.yml      
    
